### ISSUE TITLE
Collada files don't load

### ISSUE THREAD

**Issue by janga1997** [RobotWebTools/roslibjs#226]
I've tried to load the .dae file of a body, and it just doesn't seem to fetch it. I am confused as to how to specify the path of the collada files in the URDFclient, and the steps to start visualizing it in the browser.
Any help would be much appreciated. Thanks!

**Comment by kanishkaganguly** [comment]
I was having similar issues as well. The fix was simple enough after reading the following part in detail:

> Here we provide the Ros node object and TF client created above, the viewer's scene to render to, and a link to the base URL where out Collada files are too be loaded from. Note that due to browser security settings, these files must be hosted on a web server of some kind in order to be served properly. The package:// tag in the URDF file, which gives the location to import meshes from, is replaced by the base URL provided in the path parameter. For example, if you referenced a collada file in the URDF file as package:///body/meshes/body.dae, and set the path parameter as localhost:8000/, ros3djs will look for the collada file at localhost:8000/body/meshes/body.dae.

So, if you have a folder structure as **/var/www/html/web_app/** in which resides your web files as **index.html**, **js/scripts.js**, etc. you would need to keep your URDF models in a folder in your root folder named **robot_description** where **robot_description** is the name being published by your URDF parameter server.  
Inside this **robot_description** folder you will have two folders, namely **urdf** and **meshes** which contain the `.dae` files necessary.  
Also, in your `.urdf` file, you need to change the `package://` tag to match your folder structure as well. In my case, it was `package://robot_description/meshes...` and I had to remove the `robot_description` part from the file.  
Then, in your code to load the files, you have something like this:  
```
    var urdfClient = new ROS3D.UrdfClient({  
    ros : ros,  
    tfClient : tfClient,  
    path : '/web_app/',  
    rootObject : viewer.scene,  
    loader : ROS3D.COLLADA_LOADER_2  
    });
```

I think that should fix your problem.
