### ISSUE TITLE
The listener callback in subscribe is not called

### ISSUE THREAD

**Issue by Spijkervet** [RobotWebTools/roslibjs#290]
As described earlier in https://github.com/RobotWebTools/roslibjs/issues/219, I am still having issues getting console log outputs from the listener callback by following the tutorial. I am currently running on the ros-bridge server provided by the apt-get package ros-kinetic-rosbridge-server. My roslib is on the currently released version on the npm (master branch, I assume).

Any ideas what is wrong? I have done all standard installation procedures.

**Comment by T045T** [comment]
Can you give us a bit more information on your problem?

First, what tutorial are you following? You mention npm, but I don't think there is a Node tutorial yet.

Second, "all standard installation procedures" is a bit vague. What have you done exactly?
Things like the setup of your command line (which setup.bash file you sourced) may make a difference.

That said: If you're using one the `simple.html` example from this repo or the tutorial code from http://wiki.ros.org/roslibjs/Tutorials/BasicRosFunctionality , the console should print "Connection made!" before anything else.

If that's not happening, your problem is probably in the setup.
If it is, sharing the extra information I asked for may allow us to help you.

**Comment by Spijkervet** [comment]
I tried everything on a clean Ubuntu install on a virtual machine, and that seems to work fine. Still not sure what is going wrong in my own setup.

**Comment by Spijkervet** [comment]
Update: You can close this. I found out I had a different tornado version installed on my global python installation. All works fine! :)

**Comment by T045T** [comment]
That's a relief!

From your description (thanks for all the details!) I was stumped - I have a Xenial VM where I tried the same thing and couldn't reproduce the error.

Glad you figured out a solution!

**Comment by benjaminbecker** [comment]
I have the same issues as described above. How can I detect and fix the problem with the different tornado version?

**Comment by Spijkervet** [comment]
Make sure to `pip uninstall tornado` and check (e.g. in your site-packages folder) that it is completely removed.

After that, re-run `apt-get install ros-DISTRO_VERSION-rosbridge-server` to get the correct version of Tornado installed.

**Comment by benjaminbecker** [comment]
Thank you! That solved the problem within 10 seconds after 1 hour of debugging my code.

**Comment by meseta** [comment]
This fixed our issue too, thanks!
