### ISSUE TITLE
JSDoc is 404 now.

### ISSUE THREAD

**Issue by eastpiger** [RobotWebTools/roslibjs#504]
**Description**

JSDoc is 404 now.

- Library Version:
- ROS Version:
- Platform / OS:

**Steps To Reproduce**

**Expected Behavior**

**Actual Behavior**

**Comment by MatthijsBurgh** [comment]
Caused by commit https://github.com/RobotWebTools/robotwebtools.github.io/commit/4f3523dae536c0832c24c21c539a5e0020987174 of  @defunctzombie

The docs should become available again online in the (nearish) future.

You can still generate the docs yourself by running `npm run doc`.

**Comment by MatthijsBurgh** [comment]
I have uploaded the `1.2.0` docs. You can find them at http://robotwebtools.org/roslibjs/

**Comment by defunctzombie** [comment]
I don’t see any updates on the website repo - so how is this new
information hosted on the robotwebtools.org site?

I also think that domain is not the place to host docs for all the various
tools or libraries. Each library should host its own docs.

**Comment by MatthijsBurgh** [comment]
@defunctzombie The docs are hosted in the `roslibjs` repo.

Each repo has its own webpage. The `organization.github.io` repo provides the mainpage. Then every repo in the organization can provide `organization.github.io/repo`. I don't know what happens when both `organization.github.io` has a subfolder of `repo_a` and `repo_a` itself provides a page.

So the `roslibjs` docs are now on the `gh-pages` branch of this repo.

**Comment by defunctzombie** [comment]
@MatthijsBurgh wow - I had no idea this per-repo fall-through behavior existing! I thought once you setup the organization repo that would handle all requests. That's both interesting and surprising. TIL
